### ISSUE TITLE
Output indicators for DCPNI geographies

### ISSUE THREAD

**Issue by sdiby** [NeighborhoodInfoDC/DCPNI#1]
1.	Annual Number of Property Sales, Single-Family Units
2.	Annual Number of Property Sales, Condominium Units
3.	Median Sales Price, Single-Family Units
4.	Median Sales Price, Condominium Units
5.	Number of Single-Family Units
6.	Number of Condominium Units
7.	Property Crimes, per 1,000 Residents
8.	Violent Crimes, per 1,000 Residents
9.	SNAP/ TANF client counts

At the following geographies:
1.	Kenilworth (tract 96.01)
2.	Parkside (tract 96.02)
3.	Kenilworth-Parkside (tracts 96.01 and 96.02)
4.	Benning Terrace (tract 99.07)
5.	Lincoln Heights (tract 78.04)
6.	Ward 6
7.	Ward 7
8.	Ward 8
9.	DC

**Comment by rpitingolo** [comment]
@sdiby I'll review.
